security.jwt.secret=YjcyZmQ2YzdkM2U4YjI5ZjQ3YzYxYmE5ZjI0ZGMxYjczZmQ2YzdkM2U4YjI5ZjQ3YzYxYmE5ZjI0ZGMxYg==
security.jwt.issuer=repairmatch-backend
security.jwt.expiration-seconds=3600

spring.datasource.url=jdbc:postgresql://localhost:5433/repairmatch
spring.datasource.username=repairmatch
spring.datasource.password=repairmatch
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
